# Generated by Django 5.1.4 on 2026-10-08 10:18

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_shop_ownership'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0009_membership_work_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttemptBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_ends_at', models.DateTimeField(db_index=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopAdminPinResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('login_id'), condition=models.Q(('login_id__isnull', False)), name='unique_user_login_id_casefold'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('login_id__isnull', True), ('login_id__regex', '^[a-z][a-z0-9_]{2,31}$'), _connector='OR'), name='user_login_id_format_valid'),
        ),
        migrations.AddField(
            model_name='shopadminpinresetrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_pin_reset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopadminpinresetrequest',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='shopadminpinresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pin_reset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shopadminpinresetrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='unique_pending_shop_admin_pin_reset'),
        ),
        migrations.AddConstraint(
            model_name='authattemptbucket',
            constraint=models.CheckConstraint(condition=models.Q(('key__regex', '^[a-f0-9]{64}$')), name='auth_attempt_key_sha256_hex'),
        ),
        migrations.AddConstraint(
            model_name='authattemptbucket',
            constraint=models.CheckConstraint(condition=models.Q(('blocked_until__isnull', True)) | models.Q(('blocked_until__lte', models.F('window_ends_at'))), name='auth_attempt_blocked_within_window'),
        ),
        migrations.AddConstraint(
            model_name='shopadminpinresetrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='shop_pin_reset_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='shopadminpinresetrequest',
            constraint=models.CheckConstraint(condition=(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status', 'PENDING')) | models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status__in', ['APPROVED', 'REJECTED']))), name='shop_pin_reset_resolution_state'),
        ),
        migrations.AddConstraint(
            model_name='shopadminpinresetrequest',
            constraint=models.CheckConstraint(condition=models.Q(('phone__regex', '^\\+[1-9][0-9]{1,14}$')), name='shop_pin_reset_phone_e164'),
        ),
    ]
