# Generated by Django 5.1.4 on 2026-10-09 01:53

from django.db import migrations, models


def disable_viewer_only_accounts(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    TenantMember = apps.get_model("tenants", "TenantMember")
    database = schema_editor.connection.alias
    viewer_user_ids = TenantMember.objects.using(database).filter(
        role="VIEWER",
    ).values_list("user_id", flat=True)
    login_enabled_user_ids = TenantMember.objects.using(database).filter(
        role__in=("ADMIN", "STAFF"),
        is_active=True,
        deleted__isnull=True,
        tenant__is_active=True,
    ).values_list("user_id", flat=True)
    User.objects.using(database).filter(
        pk__in=viewer_user_ids,
        is_superuser=False,
    ).exclude(pk__in=login_enabled_user_ids).update(login_enabled=False)


def restore_viewer_login_eligibility(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    TenantMember = apps.get_model("tenants", "TenantMember")
    database = schema_editor.connection.alias
    viewer_user_ids = TenantMember.objects.using(database).filter(
        role="VIEWER"
    ).values_list("user_id", flat=True)
    User.objects.using(database).filter(pk__in=viewer_user_ids).update(login_enabled=True)

    # Migration 0005 installs this deferred constraint trigger on accounts_user.
    # During reverse, this RunPython executes immediately before login_enabled
    # is dropped; flush the trigger events first so PostgreSQL permits that DDL.
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SET CONSTRAINTS sgtp_user_shop_ownership_required IMMEDIATE"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authattemptbucket_shopadminpinresetrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_enabled',
            field=models.BooleanField(default=True, help_text='Whether this account is permitted to authenticate to the application.'),
        ),
        migrations.RunPython(
            disable_viewer_only_accounts,
            restore_viewer_login_eligibility,
        ),
    ]
