# Generated by Django 5.1.4 on 2026-09-27 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def create_default_supplier_and_assign(apps, schema_editor):
    Supplier = apps.get_model('tenants', 'Supplier')
    Tenant = apps.get_model('tenants', 'Tenant')
    
    # Create the singleton Supplier
    supplier, _ = Supplier.objects.get_or_create(
        singleton_lock=True,
        defaults={'name': 'Main Supplier', 'is_active': True}
    )
    
    # Assign it to all existing Tenants
    Tenant.objects.filter(supplier__isnull=True).update(supplier=supplier)

def reverse_supplier_assign(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_lock', models.BooleanField(default=True, editable=False, help_text='Enforces that only one Main Supplier can exist in the database.', unique=True)),
                ('name', models.CharField(default='Main Supplier', help_text='Name of the main supplier organization', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the main supplier is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main Supplier',
                'verbose_name_plural': 'Main Supplier',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='supplier',
            field=models.ForeignKey(help_text='The Main Supplier that owns this Shop', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='tenants.supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_lock', True)), name='supplier_singleton_lock_true'),
        ),
        migrations.RunPython(create_default_supplier_and_assign, reverse_supplier_assign),
        migrations.AlterField(
            model_name='tenant',
            name='supplier',
            field=models.ForeignKey(help_text='The Main Supplier that owns this Shop', null=False, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='tenants.supplier'),
        ),
    ]
