# Generated by Django 5.1.4 on 2026-09-27 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_supplier_and_tenant_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMember',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Shop Admin'), ('STAFF', 'Shop Staff'), ('VIEWER', 'Shop Viewer')], default='STAFF', help_text="The user's role within this Shop.", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The Shop this user is a member of.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user holding membership in the Shop.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Membership',
                'verbose_name_plural': 'Shop Memberships',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('tenant', 'user'), name='unique_tenant_user_membership')],
            },
        ),
    ]
