# Generated by Django 5.1.4 on 2026-09-28 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_membership_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenantmember',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('deleted__isnull', True), _connector='OR'), name='active_membership_cannot_be_deleted'),
        ),
    ]
