# Generated by Django 5.1.4 on 2026-09-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantmember_active_membership_cannot_be_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantmember',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shop Membership', 'verbose_name_plural': 'Shop Memberships'},
        ),
        migrations.RemoveConstraint(
            model_name='tenantmember',
            name='active_membership_cannot_be_deleted',
        ),
    ]
