# Generated by Django 5.1.4 on 2026-09-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='max_users',
            field=models.PositiveIntegerField(help_text='Maximum number of users allowed for this tenant'),
        ),
    ]
