# Generated by Django 5.1.4 on 2026-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_prevent_active_membership_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_locale',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar-KW', 'Arabic (Kuwait)'), ('bn', 'Bangla'), ('ur', 'Urdu')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_timezone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
