# Generated by Django 5.1.4 on 2026-09-29 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenant_default_currency_tenant_default_locale_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipWorkFunction",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "function_code",
                    models.CharField(
                        choices=[
                            ("SALES", "Sales"),
                            ("MEASUREMENT", "Measurement"),
                            ("CUTTING", "Cutting"),
                            ("STITCHING", "Stitching"),
                            ("FINISHING", "Finishing"),
                            ("QC", "Quality control"),
                            ("CASHIER", "Cashier"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_functions",
                        to="tenants.tenantmember",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["function_code", "created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted__isnull", True)),
                        fields=("membership", "function_code"),
                        name="uniq_active_membership_work_function",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "function_code__in",
                                [
                                    "SALES",
                                    "MEASUREMENT",
                                    "CUTTING",
                                    "STITCHING",
                                    "FINISHING",
                                    "QC",
                                    "CASHIER",
                                ],
                            )
                        ),
                        name="valid_membership_work_function_code",
                    ),
                ],
            },
        ),
    ]
