version: '3.9'

services:
  db:
    container_name: django_app_db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpasS@1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    container_name: django_app_web
    build:
      context: .
      dockerfile: ../Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    ports:
      - "8000:8000"
      - "8001:8001"
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DJANGO_ENV=development
      - DJANGO_DEBUG=True
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=devpasS@1234
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=devsecretkey
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,*
      - DJANGO_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000

volumes:
  pgdata:
