from django.urls import path

from apps.catalog.views import (
    DesignDetailView,
    DesignListCreateView,
    DesignReferenceImageView,
    DesignReferenceView,
    DesignSelectionView,
    GlobalDesignPublishView,
    GlobalDesignArchiveView,
    GlobalDesignReferenceImageView,
    GlobalDesignReferenceView,
    GlobalDesignSelectionView,
    GlobalDesignTemplatesView,
    FamilyListView,
    FamilyOptionGroupsView,
    GlobalStyleImageView,
    GlobalStyleImageUploadView,
    GlobalStyleOptionsView,
    GlobalStyleOptionDetailView,
    OptionGroupListView,
    PublishDesignVersionView,
    ShopStyleImageView,
    ShopStyleImageUploadView,
    ShopStyleOptionsView,
    ShopStyleOptionDetailView,
    ShopVariantsView,
)

urlpatterns = [
    path("catalog/families/", FamilyListView.as_view(), name="catalog-families"),
    path(
        "catalog/option-groups/",
        OptionGroupListView.as_view(),
        name="catalog-option-groups",
    ),
    path(
        "catalog/families/<uuid:family_id>/option-groups/",
        FamilyOptionGroupsView.as_view(),
        name="catalog-family-option-groups",
    ),
    path(
        "catalog/style-options/",
        GlobalStyleOptionsView.as_view(),
        name="catalog-global-style-options",
    ),
    path(
        "catalog/style-options/<uuid:option_id>/",
        GlobalStyleOptionDetailView.as_view(),
        name="catalog-global-style-option-detail",
    ),
    path(
        "catalog/style-options/<uuid:option_id>/reference-images/",
        GlobalStyleImageUploadView.as_view(),
        name="catalog-global-style-image-upload",
    ),
    path(
        "catalog/style-options/<uuid:option_id>/reference-images/<uuid:image_id>/",
        GlobalStyleImageView.as_view(),
        name="catalog-global-style-image",
    ),
    path(
        "catalog/design-templates/",
        GlobalDesignTemplatesView.as_view(),
        name="catalog-global-design-templates",
    ),
    path(
        "catalog/design-templates/<uuid:design_id>/versions/<uuid:version_id>/selections/",
        GlobalDesignSelectionView.as_view(),
        name="catalog-global-design-selections",
    ),
    path(
        "catalog/design-templates/<uuid:design_id>/versions/<uuid:version_id>/publish/",
        GlobalDesignPublishView.as_view(),
        name="catalog-global-design-publish",
    ),
    path(
        "catalog/design-templates/<uuid:design_id>/archive/",
        GlobalDesignArchiveView.as_view(),
        name="catalog-global-design-archive",
    ),
    path(
        "catalog/design-templates/<uuid:design_id>/versions/<uuid:version_id>/references/",
        GlobalDesignReferenceView.as_view(),
        name="catalog-global-design-references",
    ),
    path(
        "catalog/design-references/<uuid:reference_id>/",
        GlobalDesignReferenceImageView.as_view(),
        name="catalog-global-design-reference-image",
    ),
    path(
        "shops/<uuid:shop_id>/catalog/variants/",
        ShopVariantsView.as_view(),
        name="shop-catalog-variants",
    ),
    path(
        "shops/<uuid:shop_id>/catalog/style-options/",
        ShopStyleOptionsView.as_view(),
        name="shop-style-options",
    ),
    path(
        "shops/<uuid:shop_id>/catalog/style-options/<uuid:option_id>/",
        ShopStyleOptionDetailView.as_view(),
        name="shop-style-option-detail",
    ),
    path(
        "shops/<uuid:shop_id>/catalog/style-options/<uuid:option_id>/reference-images/",
        ShopStyleImageUploadView.as_view(),
        name="shop-style-image-upload",
    ),
    path(
        "shops/<uuid:shop_id>/catalog/style-options/<uuid:option_id>/reference-images/<uuid:image_id>/",
        ShopStyleImageView.as_view(),
        name="shop-style-image",
    ),
    path(
        "shops/<uuid:shop_id>/designs/",
        DesignListCreateView.as_view(),
        name="shop-design-list",
    ),
    path(
        "shops/<uuid:shop_id>/designs/<uuid:design_id>/",
        DesignDetailView.as_view(),
        name="shop-design-detail",
    ),
    path(
        "shops/<uuid:shop_id>/design-versions/<uuid:version_id>/selections/",
        DesignSelectionView.as_view(),
        name="shop-design-selections",
    ),
    path(
        "shops/<uuid:shop_id>/design-versions/<uuid:version_id>/publish/",
        PublishDesignVersionView.as_view(),
        name="shop-design-version-publish",
    ),
    path(
        "shops/<uuid:shop_id>/design-versions/<uuid:version_id>/references/",
        DesignReferenceView.as_view(),
        name="shop-design-version-references",
    ),
    path(
        "shops/<uuid:shop_id>/design-references/<uuid:reference_id>/",
        DesignReferenceImageView.as_view(),
        name="shop-design-reference",
    ),
]
