# Generated by Django 5.1.4 on 2026-09-30 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_membership_work_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('phone_normalized', models.CharField(blank=True, editable=False, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_normalized', models.CharField(blank=True, editable=False, max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('phone_normalized', models.CharField(blank=True, editable=False, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_normalized', models.CharField(blank=True, editable=False, max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('primary_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_persons', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'name'], name='client_shop_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'phone_normalized'], name='client_shop_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'email_normalized'], name='client_shop_email_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedperson',
            index=models.Index(fields=['tenant', 'name'], name='related_shop_name_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedperson',
            index=models.Index(fields=['tenant', 'phone_normalized'], name='related_shop_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedperson',
            index=models.Index(fields=['tenant', 'email_normalized'], name='related_shop_email_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedperson',
            index=models.Index(fields=['tenant', 'primary_client'], name='related_shop_client_idx'),
        ),
    ]
