# Generated by Django 5.1.4 on 2026-10-01 17:33

import apps.catalog.models
import apps.catalog.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_membership_work_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('source_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_designs', to='catalog.design')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.design')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_design_versions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('design_id', 'number'),
            },
        ),
        migrations.CreateModel(
            name='DesignReference',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(storage=apps.catalog.storage.PrivateReferenceStorage(), upload_to=apps.catalog.models.reference_upload_path)),
                ('mime_type', models.CharField(max_length=32)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='catalog.designversion')),
            ],
            options={
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GarmentFamily',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='FamilyOptionGroup',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.garmentfamily')),
            ],
            options={
                'ordering': ('sort_order', 'option_group__code'),
            },
        ),
        migrations.AddField(
            model_name='design',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='catalog.garmentfamily'),
        ),
        migrations.CreateModel(
            name='GarmentFamilyTranslation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'en'), ('ar-KW', 'ar-KW'), ('bn', 'bn'), ('ur', 'ur')], max_length=5)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.garmentfamily')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GarmentVariant',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.garmentfamily')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('family__code', 'code'),
            },
        ),
        migrations.AddField(
            model_name='design',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='catalog.garmentvariant'),
        ),
        migrations.CreateModel(
            name='GarmentVariantTranslation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'en'), ('ar-KW', 'ar-KW'), ('bn', 'bn'), ('ur', 'ur')], max_length=5)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.garmentvariant')),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('families', models.ManyToManyField(related_name='option_groups', through='catalog.FamilyOptionGroup', to='catalog.garmentfamily')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='familyoptiongroup',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.optiongroup'),
        ),
        migrations.CreateModel(
            name='OptionGroupTranslation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'en'), ('ar-KW', 'ar-KW'), ('bn', 'bn'), ('ur', 'ur')], max_length=5)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.optiongroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StyleOption',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='style_options', to='catalog.optiongroup')),
                ('source_style_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_style_options', to='catalog.styleoption')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('option_group__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DesignSelection',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_code', models.CharField(max_length=64)),
                ('selected_name_en', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='catalog.designversion')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.optiongroup')),
                ('style_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.styleoption')),
            ],
            options={
                'ordering': ('option_group__code', 'selected_code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StyleOptionImage',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(storage=apps.catalog.storage.PrivateReferenceStorage(), upload_to=apps.catalog.models.reference_upload_path)),
                ('mime_type', models.CharField(max_length=32)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('style_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_images', to='catalog.styleoption')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DesignSelectionImage',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='catalog.designselection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.styleoptionimage')),
            ],
        ),
        migrations.CreateModel(
            name='StyleOptionTranslation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'en'), ('ar-KW', 'ar-KW'), ('bn', 'bn'), ('ur', 'ur')], max_length=5)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('style_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.styleoption')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.UniqueConstraint(fields=('design', 'number'), name='catalog_design_version_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True), ('status', 'DRAFT')), fields=('design',), name='catalog_one_draft_per_design'),
        ),
        migrations.AddConstraint(
            model_name='garmentfamilytranslation',
            constraint=models.UniqueConstraint(fields=('family', 'locale'), name='catalog_family_locale_uniq'),
        ),
        migrations.AddConstraint(
            model_name='garmentvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True), ('tenant__isnull', True)), fields=('family', 'code'), name='catalog_global_variant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='garmentvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'family', 'code'), name='catalog_shop_variant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='garmentvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True), ('is_default', True), ('tenant__isnull', True)), fields=('family',), name='catalog_one_global_default_variant'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['tenant', 'status', 'name'], name='catalog_des_tenant__e21fd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='garmentvarianttranslation',
            constraint=models.UniqueConstraint(fields=('variant', 'locale'), name='catalog_variant_locale_uniq'),
        ),
        migrations.AddConstraint(
            model_name='familyoptiongroup',
            constraint=models.UniqueConstraint(fields=('family', 'option_group'), name='catalog_family_option_group_uniq'),
        ),
        migrations.AddConstraint(
            model_name='optiongrouptranslation',
            constraint=models.UniqueConstraint(fields=('option_group', 'locale'), name='catalog_group_locale_uniq'),
        ),
        migrations.AddConstraint(
            model_name='styleoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True), ('tenant__isnull', True)), fields=('option_group', 'code'), name='catalog_global_style_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='styleoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'option_group', 'code'), name='catalog_shop_style_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='designselection',
            constraint=models.UniqueConstraint(fields=('version', 'option_group', 'style_option'), name='catalog_selection_unique_option'),
        ),
        migrations.AddConstraint(
            model_name='designselectionimage',
            constraint=models.UniqueConstraint(fields=('selection', 'source_image'), name='catalog_selection_image_uniq'),
        ),
        migrations.AddConstraint(
            model_name='styleoptiontranslation',
            constraint=models.UniqueConstraint(fields=('style_option', 'locale'), name='catalog_style_locale_uniq'),
        ),
    ]
