# Generated by Django 5.1.4 on 2026-10-01 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_catalog_defaults'),
        ('tenants', '0009_membership_work_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignVersionTranslation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'en'), ('ar-KW', 'ar-KW'), ('bn', 'bn'), ('ur', 'ur')], max_length=5)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ('-created_at', 'id')},
        ),
        migrations.RemoveIndex(
            model_name='design',
            name='catalog_des_tenant__e21fd7_idx',
        ),
        migrations.RemoveField(
            model_name='design',
            name='name',
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['tenant', 'status', 'family'], name='catalog_des_tenant__982ec5_idx'),
        ),
        migrations.AddField(
            model_name='designversiontranslation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designversiontranslation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designversiontranslation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.designversion'),
        ),
        migrations.AddConstraint(
            model_name='designversiontranslation',
            constraint=models.UniqueConstraint(fields=('version', 'locale'), name='catalog_design_locale_uniq'),
        ),
    ]
