# Generated by Django 5.1.4 on 2026-10-01 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_designversiontranslation_alter_design_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='familyoptiongroup',
            name='catalog_family_option_group_uniq',
        ),
        migrations.AddConstraint(
            model_name='familyoptiongroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('family', 'option_group'), name='catalog_family_option_group_uniq'),
        ),
    ]
