# Generated by Django 5.1.4 on 2026-10-02 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_designselectiontranslation"),
        ("clients", "0001_initial"),
        ("tenants", "0009_membership_work_functions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementDefinition",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64)),
                ("group_code", models.CharField(blank=True, max_length=48)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "code", "id"),
            },
        ),
        migrations.CreateModel(
            name="MeasurementDefinitionMapping",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mappings",
                        to="catalog.measurementdefinition",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurement_mappings",
                        to="catalog.garmentfamily",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurement_mappings",
                        to="catalog.garmentvariant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measurementdefinition",
            name="families",
            field=models.ManyToManyField(
                related_name="measurement_definitions",
                through="catalog.MeasurementDefinitionMapping",
                to="catalog.garmentfamily",
            ),
        ),
        migrations.CreateModel(
            name="MeasurementDefinitionTranslation",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ar-KW", "Arabic (Kuwait)"),
                            ("bn", "Bangla"),
                            ("ur", "Urdu"),
                        ],
                        max_length=5,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.measurementdefinition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementProfile",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurement_profiles",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurement_profiles",
                        to="catalog.garmentfamily",
                    ),
                ),
                (
                    "related_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurement_profiles",
                        to="clients.relatedperson",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurement_profiles",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurement_profiles",
                        to="catalog.garmentvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="MeasurementSet",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "copied_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies",
                        to="catalog.measurementset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sets",
                        to="catalog.measurementprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-version", "id"),
            },
        ),
        migrations.CreateModel(
            name="MeasurementValue",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("definition_code_snapshot", models.CharField(max_length=64)),
                ("label_snapshot", models.CharField(max_length=120)),
                ("value", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        choices=[("INCH", "Inch"), ("CM", "Centimetre")], max_length=4
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="catalog.measurementdefinition",
                    ),
                ),
                (
                    "measurement_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="catalog.measurementset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("definition_code_snapshot", "id"),
            },
        ),
        migrations.CreateModel(
            name="MeasurementValueTranslationSnapshot",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ar-KW", "Arabic (Kuwait)"),
                            ("bn", "Bangla"),
                            ("ur", "Urdu"),
                        ],
                        max_length=5,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "value_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="label_translations",
                        to="catalog.measurementvalue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("code", models.SlugField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        default="ACTIVE",
                        max_length=8,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("code__gt", ""), ("deleted__isnull", True)),
                        fields=("tenant", "code"),
                        name="material_shop_code_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("ACTIVE", "ARCHIVED"))),
                        name="material_status_valid",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="measurementdefinitionmapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted__isnull", True), ("variant__isnull", True)
                ),
                fields=("definition", "family"),
                name="measure_map_family_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementdefinitionmapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted__isnull", True), ("variant__isnull", False)
                ),
                fields=("definition", "family", "variant"),
                name="measure_map_variant_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True), ("tenant__isnull", True)),
                fields=("code",),
                name="measurement_global_code_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted__isnull", True), ("tenant__isnull", False)
                ),
                fields=("tenant", "code"),
                name="measurement_shop_code_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementdefinitiontranslation",
            constraint=models.UniqueConstraint(
                fields=("definition", "locale"), name="measurement_def_locale_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("client__isnull", False), ("related_person__isnull", True)
                    ),
                    models.Q(
                        ("client__isnull", True), ("related_person__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="measurement_profile_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client__isnull", False),
                    ("deleted__isnull", True),
                    ("variant__isnull", True),
                ),
                fields=("tenant", "client", "family"),
                name="measure_profile_client_base_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client__isnull", False),
                    ("deleted__isnull", True),
                    ("variant__isnull", False),
                ),
                fields=("tenant", "client", "family", "variant"),
                name="measure_profile_client_variant_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted__isnull", True),
                    ("related_person__isnull", False),
                    ("variant__isnull", True),
                ),
                fields=("tenant", "related_person", "family"),
                name="measure_profile_person_base_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted__isnull", True),
                    ("related_person__isnull", False),
                    ("variant__isnull", False),
                ),
                fields=("tenant", "related_person", "family", "variant"),
                name="measure_profile_person_variant_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementset",
            constraint=models.UniqueConstraint(
                fields=("profile", "version"), name="measurement_set_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementset",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="measurement_set_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementvalue",
            constraint=models.UniqueConstraint(
                fields=("measurement_set", "definition"),
                name="measurement_value_def_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementvalue",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit__in", ("INCH", "CM"))),
                name="measurement_value_unit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementvaluetranslationsnapshot",
            constraint=models.UniqueConstraint(
                fields=("value_record", "locale"), name="measure_value_locale_uniq"
            ),
        ),
    ]
