# Generated by Django 5.1.4 on 2026-10-02 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_seed_measurement_definitions"),
        ("tenants", "0009_membership_work_functions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryBalance",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "on_hand",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "reserved",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
            ],
            options={
                "ordering": ("material_id",),
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening stock"),
                            ("STOCK_IN", "Stock in"),
                            ("RESERVE", "Reserve"),
                            ("RELEASE", "Release"),
                            ("CONSUME", "Consume"),
                            ("RETURN", "Return"),
                            ("ADJUSTMENT_IN", "Adjustment in"),
                            ("ADJUSTMENT_OUT", "Adjustment out"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_snapshot",
                    models.CharField(
                        choices=[
                            ("METRE", "Metre"),
                            ("YARD", "Yard"),
                            ("PIECE", "Piece"),
                            ("ROLL", "Roll"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "on_hand_before",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("on_hand_after", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "reserved_before",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "reserved_after",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("reason", models.CharField(max_length=300)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="material",
            name="inventory_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FABRIC", "Fabric"),
                    ("BUTTON", "Button"),
                    ("ZIP", "Zip"),
                    ("THREAD", "Thread"),
                    ("HOOK", "Hook"),
                    ("INTERLINING", "Interlining"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="stock_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("METRE", "Metre"),
                    ("YARD", "Yard"),
                    ("PIECE", "Piece"),
                    ("ROLL", "Roll"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("inventory_category", ""), ("stock_unit", "")),
                    models.Q(
                        (
                            "inventory_category__in",
                            [
                                "FABRIC",
                                "BUTTON",
                                "ZIP",
                                "THREAD",
                                "HOOK",
                                "INTERLINING",
                                "OTHER",
                            ],
                        ),
                        ("stock_unit__in", ["METRE", "YARD", "PIECE", "ROLL"]),
                    ),
                    _connector="OR",
                ),
                name="material_inventory_classification_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["tenant", "inventory_category", "status"],
                name="catalog_material_inventory_idx",
            ),
        ),
        migrations.AddField(
            model_name="inventorybalance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorybalance",
            name="material",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_balance",
                to="catalog.material",
            ),
        ),
        migrations.AddField(
            model_name="inventorybalance",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_balances",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="inventorybalance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="updated_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="catalog.material",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="updated_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybalance",
            index=models.Index(
                fields=["tenant", "on_hand"], name="catalog_inv_tenant__9ae291_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorybalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("on_hand__gte", 0)),
                name="inventory_balance_on_hand_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorybalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__gte", 0)),
                name="inventory_balance_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorybalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__lte", models.F("on_hand"))),
                name="inventory_balance_reserved_lte_on_hand",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "material", "created_at"],
                name="catalog_sto_tenant__de21b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["material", "movement_type", "created_at"],
                name="catalog_sto_materia_16d810_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movement_type__in",
                        [
                            "OPENING",
                            "STOCK_IN",
                            "RESERVE",
                            "RELEASE",
                            "CONSUME",
                            "RETURN",
                            "ADJUSTMENT_IN",
                            "ADJUSTMENT_OUT",
                        ],
                    )
                ),
                name="stock_movement_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_snapshot__in", ["METRE", "YARD", "PIECE", "ROLL"])
                ),
                name="stock_movement_unit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stock_movement_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("on_hand_before__gte", 0),
                    ("on_hand_after__gte", 0),
                    ("reserved_before__gte", 0),
                    ("reserved_after__gte", 0),
                ),
                name="stock_movement_snapshots_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reserved_before__lte", models.F("on_hand_before")),
                    ("reserved_after__lte", models.F("on_hand_after")),
                ),
                name="stock_movement_reserved_lte_on_hand",
            ),
        ),
    ]
