# Generated by Django 5.1.4 on 2026-10-02 17:35

import django.db.models.functions.math
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_inventorybalance_stockmovement_and_more"),
        ("tenants", "0009_membership_work_functions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_snapshot__in", ("METRE", "YARD")),
                    ("quantity", django.db.models.functions.math.Floor("quantity")),
                    _connector="OR",
                ),
                name="stock_movement_piece_roll_whole",
            ),
        ),
    ]
