# Generated by Django 5.1.4 on 2026-10-03 02:20

import apps.catalog.models
import apps.catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_stockmovement_stock_movement_piece_roll_whole"),
    ]

    operations = [
        migrations.AddField(
            model_name="garmentfamily",
            name="image",
            field=models.FileField(
                blank=True,
                storage=apps.catalog.storage.PrivateReferenceStorage(),
                upload_to=apps.catalog.models.family_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="garmentfamily",
            name="image_byte_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garmentfamily",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garmentfamily",
            name="image_mime_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="garmentfamily",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garmentfamily",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
