# Generated by Django 5.1.4 on 2026-10-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_garmentfamily_image_garmentfamily_image_byte_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
