# Generated by Django 5.1.4 on 2026-10-04 17:26

import apps.catalog.models
import apps.catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_privatemediaupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designreference",
            name="image",
            field=models.FileField(
                max_length=512,
                storage=apps.catalog.storage.PrivateReferenceStorage(),
                upload_to=apps.catalog.models.reference_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="styleoptionimage",
            name="image",
            field=models.FileField(
                max_length=512,
                storage=apps.catalog.storage.PrivateReferenceStorage(),
                upload_to=apps.catalog.models.reference_upload_path,
            ),
        ),
    ]
