# Generated by Django 5.1.4 on 2026-10-05 12:24

from django.conf import settings
from django.db import migrations, models


def mark_existing_primary(apps, schema_editor):
    Image = apps.get_model("catalog", "StyleOptionImage")
    database = schema_editor.connection.alias
    option_ids = (
        Image.objects.using(database)
        .values_list("style_option_id", flat=True)
        .distinct()
    )
    for option_id in option_ids.iterator():
        image = (
            Image.objects.using(database)
            .filter(style_option_id=option_id)
            .order_by("sort_order", "created_at", "id")
            .first()
        )
        if image:
            Image.objects.using(database).filter(pk=image.pk).update(is_primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_private_reference_path_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="styleoptionimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_primary, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="styleoptionimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("style_option",),
                name="catalog_style_option_one_primary_image",
            ),
        ),
    ]
