from django.contrib.auth.models import BaseUserManager
from ..identity import normalize_email, normalize_login_id


class UserManager(BaseUserManager):
    def create_user(self, email=None, password=None, **extra_fields):
        first_name = (extra_fields.get("first_name") or "").strip()
        if not first_name:
            raise ValueError("The first_name field must be set")
        extra_fields["first_name"] = first_name
        extra_fields["last_name"] = (extra_fields.get("last_name") or "").strip()
        email = normalize_email(email)
        extra_fields["phone"] = self._normalize_phone(extra_fields.get("phone"))
        if extra_fields.get("is_superuser") and (not email or not extra_fields["phone"]):
            raise ValueError("Main Supplier accounts require email and phone")
        if "user_code" in extra_fields:
            raise ValueError("user_code is generated by the system")

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db, force_insert=True)
        return user

    @staticmethod
    def _normalize_phone(value):
        from ..phone_numbers import InvalidUserPhone, normalize_user_phone

        try:
            return normalize_user_phone(value)
        except InvalidUserPhone as exc:
            raise ValueError(str(exc)) from exc

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        normalized_email = normalize_email(email)
        normalized_phone = self._normalize_phone(extra_fields.get("phone"))
        has_first_name = bool((extra_fields.get("first_name") or "").strip())
        if not normalized_email or not normalized_phone or not has_first_name:
            raise ValueError("Superusers require email, phone, and first_name.")

        if extra_fields.get("login_id"):
            try:
                extra_fields["login_id"] = normalize_login_id(extra_fields["login_id"])
            except ValueError as exc:
                raise ValueError(
                    "New Main Supplier accounts require a valid Login ID."
                ) from exc
            # Django's createsuperuser command validates operator-entered
            # bootstrap passwords against the normal password validators. The
            # first authenticated operation must therefore replace that
            # bootstrap secret with the required six-digit PIN.
            extra_fields["must_change_password"] = True

        extra_fields["phone"] = normalized_phone
        return self.create_user(normalized_email, password, **extra_fields)
